### ISSUE TITLE
Fails to install OpenResty

### ISSUE THREAD

**Issue by chris-jansson** [openresty/homebrew-brew#5]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
I am trying to install OpenResty via Homebrew. When I run the install command, I get this error:

```
Updating Homebrew...
Error: undefined method `name' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:186:in `block in initialize'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:185:in `map'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:185:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:414:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:414:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:310:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:490:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:49:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:45:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:45:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:129:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### The complete command that you issued:

```
brew tap openresty/brew
brew install openresty
```

#### Gist with output of `brew doctor`:
https://gist.github.com/chris-jansson/b2196daf92dd3a227f2326e0ed4c80a7

#### Link output by `brew gist-logs <formula>`:

```
Error: undefined method `name' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:186:in `block in initialize'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:185:in `map'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:185:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:414:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:414:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:379:in `canonical_name'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:375:in `to_rack'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:64:in `resolve'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:57:in `block in resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:56:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:56:in `resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:135:in `gist_logs'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew config`:

```
HOMEBREW_VERSION: 1.8.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a51a1908f318003f0fd7eb52d493d5c6ef8637a4
Core tap last commit: 80 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
```

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/denji/homebrew-nginx/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by chris-jansson** [comment]
Also, I reviewed the [Common Issues](https://docs.brew.sh/Common-Issues) page, and noted this looks similar to the "`brew upgrade` errors out" issue. I attempted that solution, but it did not work:

    $ cd $(brew --repository)/Library/Contributions/examples
    -bash: cd: /usr/local/Homebrew/Library/Contributions/examples: No such file or directory

**Comment by agentzh** [comment]
@moonming Will you look into this?

**Comment by zhuizhuhaomeng** [comment]
cleanup old issue.
